name = "blog-lacolaco-net"

compatibility_date = "2025-06-04"
main = "./dist/_worker.js/index.js"
preview_urls = true
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
