name: deploy

on: 
  push:
    branches: 
      - master
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build
    - run: yarn deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
