name: pr-check

on: pull_request

jobs:
  check-notion-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: yarn
      - run: yarn install
        working-directory: notion-gateway
      - run: yarn test
        working-directory: notion-gateway
